# Generated by Django 5.0.1 on 2024-02-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beginner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='static/images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
