# Generated by Django 5.0.1 on 2024-02-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beginner',
            name='Title',
        ),
    ]
