# Generated by Django 5.0.1 on 2024-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0002_remove_beginner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginner',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='beginner',
            name='MainImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
