# Generated by Django 5.0.2 on 2024-02-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0003_alter_beginner_image_alter_beginner_mainimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beginner',
            new_name='BeginnersData',
        ),
    ]
