# Generated by Django 5.0.2 on 2024-02-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0005_beginnersdata_focusfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeginnersChest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='BeginnersData',
            new_name='BeginnersAbs',
        ),
    ]
