# Generated by Django 5.0.2 on 2024-02-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0007_alter_beginnerschest_focusfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeginnersArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
