# Generated by Django 5.0.2 on 2024-02-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0008_beginnersarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvancedArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvancedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvancedChest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvancedLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeginnersBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeginnersLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntermediateAbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntermediateArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntermediateBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntermediateChest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntermediateLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainImage', models.ImageField(upload_to='images/')),
                ('MainTitle', models.CharField(max_length=255)),
                ('Text1', models.TextField()),
                ('Text2', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('FocusFields', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
