# Generated by Django 5.0.2 on 2024-03-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0009_advancedabs_advancedarm_advancedback_advancedchest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvancedAbs',
        ),
        migrations.DeleteModel(
            name='AdvancedArm',
        ),
        migrations.DeleteModel(
            name='AdvancedBack',
        ),
        migrations.DeleteModel(
            name='AdvancedChest',
        ),
        migrations.DeleteModel(
            name='AdvancedLeg',
        ),
    ]
